region: us-east-1
instance_type: t3.large
launch_template_id: lt-0a1730f52131e3465
min_capacity: 1
desired_capacity: 2
max_capacity: 30
scaling_policy:
  scale_out_threshold: 50
  scale_in_threshold: 20
vpc:
  cidr: 10.0.0.0/16
  subnets:
    - cidr: 10.0.1.0/24
      az: us-east-1a
    - cidr: 10.0.2.0/24
      az: us-east-1b
